### ISSUE TITLE
Highlight color for badges

### ISSUE THREAD

**Issue by LangLangBart** [0b5vr/vscode-monokai-sharp#2]
Thanks for creating this theme.  :clap:

Have you any thoughts on changing the color for badges? In my opinion the color should be more eye catching, currently (default) it is rather dull.
See images below for more clarity, the examples (1,2) are just something I have been experimenting with.

<img src="https://ttm.sh/qpY.jpg" width="600">

(default, as it is currently set)
```json
    "badge.foreground": "#191a1f",
    "badge.background": "#d0edff",
	...
    "activityBarBadge.foreground": "#191a1f",
    "activityBarBadge.background": "#d0edff",
```

For example:
(1)
```json
    "badge.foreground": "#eeee9c",
    "badge.background": "#4a5000",
	...
    "activityBarBadge.foreground": "#eeee9c",
    "activityBarBadge.background": "#4a5000",
```

(2)
```json
    "badge.foreground": "#4a5000",
    "badge.background": "#f7f025",
	...
    "activityBarBadge.foreground": "#4a5000",
    "activityBarBadge.background": "#f7f025",
```

I can do a PR, just let me know if this is something you really want to change or not.
PS: Tested color contrast with (AAA Guidelines && Small Text): https://www.learnui.design/tools/accessible-color-generator.html

**Comment by 0b5vr** [comment]
The white is my preference. I probably don't want to change this.

**Comment by LangLangBart** [comment]
Ok
